/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#pragma mark -

/*
 * File: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
 * UUID: 47674D2C-BE88-388E-B1B0-03F08BFFE5FD
 * Arch: x86_64
 *       Current version: 283.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *       SDK version: 0.0.0
 *
 */

//
// This file does not contain any Objective-C runtime information.
//
